---   
- name: get hostname
  debug:
    msg: "{{ inventory_hostname }}" 

- name: install Opensmtpd
  apt:
    name: "opensmtpd"
    state: present
    update_cache: yes
  register: installed_opensmtpd_status
